version: '3'
services:
  maria:
    image: mysql:5.7
    container_name: real-my-sql
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rms
      TZ: Asia/Seoul
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init/:/docker-entrypoint-initdb.d/